"""recipes

Revision ID: 83a3c4b6fcd9
Revises: 4fa27d0b049a
Create Date: 2024-12-22 16:52:17.194632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a3c4b6fcd9'
down_revision = '4fa27d0b049a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('servings', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('prep_time', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('recipe_text', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('recipe_text')
        batch_op.drop_column('prep_time')
        batch_op.drop_column('servings')
        batch_op.drop_column('price')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
